AWSTemplateFormatVersion: 2010-09-09
Description: twitter bot by lambda.
Transform:
  - AWS::Serverless-2016-10-31
Resources:
  forTwitterBot:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/index.handler
      Runtime: nodejs12.x
      MemorySize: 128
      Timeout: 100
      Description: A Lambda function that returns a static string.
      Policies:
        - AWSLambdaBasicExecutionRole
      Environment:
        Variables:
          API_KEY:
            Ref: API_KEY
          API_KEY_SECRET: 
            Ref: API_KEY_SECRET
          ACCESS_TOKEN:
            Ref: ACCESS_TOKEN
          ACCESS_TOKEN_SECRET: 
            Ref: ACCESS_TOKEN_SECRET
Parameters:
  API_KEY:
    Type: String
  API_KEY_SECRET:
    Type: String
  ACCESS_TOKEN:
    Type: String
  ACCESS_TOKEN_SECRET:
    Type: String




#     Environment:
#         Variables:
#           TWITTER_API_KEY:
#             Ref: TwitterApiKey
#           TWITTER_API_KEY_SECRET:
#             Ref: TwitterApiKeySecret
#           BEARER_TOKEN: 
#             Ref: BearerToken
# Parameters:
#   TwitterApiKey:
#     Type: String
#   TwitterApiKeySecret:
#     Type: String
#   BearerToken:
#     Type: String